services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payload-cms
    volumes:
      - ./payload:/app
    ports:
      - "3002:3002"
    env_file:
      - ".env"
    restart: unless-stopped
